name: Compile iOS Tweak Packages

on:
  workflow_dispatch: # Allows you to manually trigger the build with a button click

jobs:
  build:
    runs-on: macos-latest # Using macOS provides Xcode native tools out of the box

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Install Theos Framework
        run: |
          git clone --recursive https://github.com $GITHUB_WORKSPACE/theos
          
      - name: Download Stable iOS SDK
        run: |
          git clone https://github.com $GITHUB_WORKSPACE/theos/sdks

      - name: Compile Tweak Architecture payload
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make package FINALPACKAGE=1

      - name: Upload Finished Compiled Package
        uses: actions/upload-artifact@v4
        with:
          name: 3DAppVersionSpoofer-Compiled-Deb
          path: packages/*.deb
