name: Compile iOS Tweak Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Clear Pre-Existing Environments
        run: |
          rm -rf ${{ github.workspace }}/theos

      - name: Install Pure Theos Framework
        run: |
          git clone --recursive https://github.com/theos/theos.git ${{ github.workspace }}/theos
          
      - name: Download Pure iOS SDK Packs
        run: |
          rm -rf ${{ github.workspace }}/theos/sdks
          git clone https://github.com ${{ github.workspace }}/theos/sdks

      - name: Force Custom Pipeline Compilation
        run: |
          export THEOS=${{ github.workspace }}/theos
          # Clean any local cache variables that break compilation flags
          make clean
          make package FINALPACKAGE=1
          
      - name: Export Finished Compiled Asset
        uses: actions/upload-artifact@v4
        with:
          name: 3DAppVersionSpoofer-Compiled-Deb
          path: packages/*.deb
