name: Compile iOS Tweak Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Download Pure Theos Framework Archive
        run: |
          curl -L "https://github.com" -o pure_theos.zip
          unzip -q pure_theos.zip
          mv theos-master ${{ github.workspace }}/clean_theos_env
          rm -rf pure_theos.zip

      - name: Download Pure iOS SDK Archive Packs
        run: |
          curl -L "https://github.com" -o pure_sdks.zip
          unzip -q pure_sdks.zip
          rm -rf ${{ github.workspace }}/clean_theos_env/sdks
          mv sdks-master ${{ github.workspace }}/clean_theos_env/sdks
          rm -rf pure_sdks.zip

      - name: Isolate and Compile Tweak Architecture
        run: |
          export THEOS=${{ github.workspace }}/clean_theos_env
          make clean
          make package FINALPACKAGE=1
          
      - name: Export Finished Compiled Package
        uses: actions/upload-artifact@v4
        with:
          name: 3DAppVersionSpoofer-Compiled-Deb
          path: packages/*.deb
